name: CI

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest  
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Test Python application
        run: python -m py_compile app.py
      
      - name: Test SSH connection
        run: |
          whoami
          echo "$HOME"
          pwd
          ls -la
          mkdir -p "$HOME/.ssh"
          echo "SSH directory created"
                  
